<a href="https://colab.research.google.com/github/MonikaLamba/Python-Programming/blob/main/python_numpy_multidim_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy — Multidimensional Arrays (Beginner Friendly)

*The NumPy Library · 2-D arrays · lots of examples*

A **multidimensional array** has more than one row. The most common is the
**2-D array** — a grid of **rows and columns**, just like a table or a maths
*matrix*:

```
        col0  col1  col2
 row0 [   1     2     3  ]
 row1 [   4     5     6  ]
```

**Topics**
1. Creating 2-D arrays  
2. Array information (shape, size…)  
3. Accessing elements (rows, columns, cells)  
4. Mathematical operators (element-wise, broadcasting, matrix multiply)  
5. Useful functions (and the important **axis** idea)  
6. Relational (comparison) operators & filtering

**How to use it:** read the short message, then run the small code box below it
with **Shift + Enter**. Change the values and run again. Run the cells top to bottom.

---

First, **import** NumPy with its usual nickname `np`:

In [1]:
import numpy as np
print("NumPy is ready! Version:", np.__version__)

NumPy is ready! Version: 2.1.3


## 1. Creating 2-D Arrays

A 2-D array is made from a **list of lists** — each inner list is one **row**.

Make a 2-D array from nested lists. Notice how it prints as a neat grid:

In [2]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


**`np.zeros((rows, cols))`** and **`np.ones((rows, cols))`** — note the shape is
given as a pair `(rows, cols)`:

In [3]:
print(np.zeros((2, 3)))
print(np.ones((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**`np.full((rows, cols), value)`** fills a grid with any value:

In [4]:
print(np.full((2, 2), 7))

[[7 7]
 [7 7]]


**`np.eye(n)`** makes an *identity matrix* — 1s on the diagonal, 0s elsewhere:

In [5]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**`reshape`** turns a flat range of numbers into a grid.
Here 12 numbers become 3 rows × 4 columns:

In [6]:
print(np.arange(12).reshape(3, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


A **random** 2-D array (a seed makes the numbers repeatable):

In [7]:
np.random.seed(0)
print(np.random.randint(1, 10, (2, 3)))

[[6 1 4]
 [4 8 4]]


## 2. Array Information

For 2-D arrays, `shape` is the most useful detail — it tells you the number of
**rows and columns**.

`ndim` = number of dimensions (2), `shape` = `(rows, cols)`, `size` = total
number of elements:

In [8]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("ndim :", arr.ndim)
print("shape:", arr.shape)
print("size :", arr.size)
print("dtype:", arr.dtype)

ndim : 2
shape: (2, 3)
size : 6
dtype: int64


## 3. Accessing Elements

To reach one cell in a 2-D array you give **two positions**: `arr[row, column]`
(both start at 0).

Get single cells with `arr[row, col]`:

In [9]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print(arr[0, 0])    # row 0, col 0
print(arr[1, 2])    # row 1, col 2
print(arr[-1, -1])  # last row, last col

10
60
90


Get a **whole row** by giving just the row number:

In [10]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print(arr[1])       # the second row

[40 50 60]


Get a **whole column** with `arr[:, col]` — the `:` means "all rows":

In [11]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print(arr[:, 0])    # the first column

[10 40 70]


**Slice a smaller grid** with `arr[row_start:row_stop, col_start:col_stop]`:

In [12]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print(arr[0:2, 1:3])   # first two rows, last two columns

[[20 30]
 [50 60]]


Arrays are **changeable** — set one cell to a new value:

In [13]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])
arr[0, 0] = 100
print(arr)

[[100  20  30]
 [ 40  50  60]]


You can change a **whole row** (or column) at once:

In [14]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])
arr[1] = [0, 0, 0]
print(arr)

[[10 20 30]
 [ 0  0  0]]


## 4. Mathematical Operators

Just like 1-D arrays, maths happens on **every element at once** — no loops needed.

Add or multiply a number to **every** element (this is called *broadcasting*):

In [15]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr + 10)
print(arr * 2)

[[11 12 13]
 [14 15 16]]
[[ 2  4  6]
 [ 8 10 12]]


Add **two arrays of the same shape** — matching cells are combined:

In [16]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[10, 20],
              [30, 40]])
print(a + b)

[[11 22]
 [33 44]]


**Broadcasting** a row: a 1-D row is added to **every** row of the grid:

In [17]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
row = np.array([10, 20, 30])
print(arr + row)

[[11 22 33]
 [14 25 36]]


**Important:** `*` multiplies **cell by cell**, while `@` does true
**matrix multiplication** — they are different!

In [18]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
print("Element-wise (*):")
print(A * B)
print("Matrix multiply (@):")
print(A @ B)

Element-wise (*):
[[ 5 12]
 [21 32]]
Matrix multiply (@):
[[19 22]
 [43 50]]


**Transpose** with `.T` flips rows into columns:

In [19]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


## 5. Useful Functions (and the `axis` idea)

Functions like `sum` and `mean` work on the whole grid — but with 2-D arrays you
can also apply them **down columns** or **across rows** using **`axis`**:

```
axis=0   ↓  goes DOWN the rows   → one result per COLUMN
axis=1   →  goes ACROSS columns  → one result per ROW
```

With **no axis**, the function uses the whole grid:

In [20]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Sum of everything:", np.sum(arr))

Sum of everything: 21


**`axis=0`** works down each **column** (gives one number per column):

In [21]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(np.sum(arr, axis=0))

[5 7 9]


**`axis=1`** works across each **row** (gives one number per row):

In [22]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(np.sum(arr, axis=1))

[ 6 15]


The same axis idea works for `mean`, `max`, `min`, and more:

In [23]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])
print("Column means:", np.mean(arr, axis=0))
print("Row maxes   :", np.max(arr, axis=1))

Column means: [25. 35. 45.]
Row maxes   : [30 60]


**`np.sqrt`** works on every element, and **`flatten()`** turns a 2-D grid back
into a 1-D array:

In [24]:
arr = np.array([[1, 4],
                [9, 16]])
print(np.sqrt(arr))
print("Flattened:", arr.flatten())

[[1. 2.]
 [3. 4.]]
Flattened: [ 1  4  9 16]


## 6. Relational (Comparison) Operators

Comparing a 2-D array with a value checks **every cell** and returns a grid of
`True`/`False`. This is the key to **filtering** a table of data.

**`arr > 25`** checks every cell and returns a matching grid of True/False:

In [25]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])
print(arr > 25)

[[False False  True]
 [ True  True  True]]


**Boolean indexing** — pull out only the values that pass the test.
The result is a flat 1-D array of the matches:

In [26]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])
print(arr[arr > 25])

[30 40 50 60]


**Combine conditions** with `&` (and) and `|` (or), each in parentheses:

In [27]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])
print(arr[(arr > 15) & (arr < 55)])

[20 30 40 50]


**Count** how many cells pass a test (`True` counts as 1):

In [28]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])
print(np.sum(arr > 25))

4


**`np.any`** ("is any True?") and **`np.all`** ("are all True?") — and they take
an `axis` too:

In [29]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])
print(np.any(arr > 55))          # anywhere in the grid?
print(np.all(arr > 5))           # every cell?
print(np.all(arr > 5, axis=1))   # per row

True
True
[ True  True]


---

## Well done!

You have learned and run, for **multidimensional (2-D) NumPy arrays**:

- **Creating** — nested lists, `zeros`, `ones`, `full`, `eye`, `reshape`, random
- **Array info** — `ndim`, `shape` (rows, cols), `size`, `dtype`
- **Accessing** — `arr[row, col]`, whole rows, whole columns (`arr[:, c]`),
  sub-grids, and changing values
- **Maths operators** — element-wise `+ - * /`, adding arrays, broadcasting,
  element-wise `*` vs matrix `@`, and transpose `.T`
- **Functions & axis** — `sum`/`mean`/`max`/`min` on the whole grid, or per column
  (`axis=0`) / per row (`axis=1`), plus `sqrt` and `flatten`
- **Relational operators** — `>`, boolean indexing, `&`/`|`, counting, `any`/`all`

### Try it yourself
1. Make a 3×3 grid of the numbers 1 to 9 using `np.arange(1, 10).reshape(3, 3)`.
2. From that grid, print the second row and the last column.
3. Find the sum of each column (`axis=0`) and each row (`axis=1`).
4. Multiply the whole grid by 10.
5. Keep only the values greater than 5 using boolean indexing.

You can now work with tables of numbers — the heart of data science! 🐍

*(Good to know: arrays can go beyond 2-D — a 3-D array is like a stack of grids,
using shapes such as `(2, 3, 4)`. Everything you learned here still applies.)*