<a href="https://colab.research.google.com/github/MonikaLamba/Python-Programming/blob/main/python_numpy_1d_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy — 1-D Arrays (Beginner Friendly)

*The NumPy Library · lots of examples*

**NumPy** (short for *Numerical Python*) is a library for doing fast maths on lots
of numbers at once. Its main tool is the **array**. A **1-D array** is a single row
of numbers — like a Python list, but faster and able to do maths on every element
at the same time.

**Topics**
1. Creating 1-D arrays  
2. Array information (size, type…)  
3. Accessing elements (indexing & slicing)  
4. Mathematical operators (element-wise maths)  
5. Useful functions  
6. Relational (comparison) operators & filtering

**How to use it:** read the short message, then run the small code box below it
with **Shift + Enter**. Change the values and run again — that's the best way to
learn. Run the cells from top to bottom.

---

First, **import** NumPy. Almost everyone gives it the short nickname `np`:

In [34]:
import numpy as np
print("NumPy is ready! Version:", np.__version__)

NumPy is ready! Version: 2.1.3


## 1. Creating 1-D Arrays

There are several handy ways to make a 1-D array.

The most common way — turn a **list** into an array with `np.array()`:

In [35]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


It is a special NumPy type called an **ndarray**:

In [36]:
arr = np.array([10, 20, 30, 40, 50])
print(type(arr))

<class 'numpy.ndarray'>


**`np.arange(start, stop, step)`** makes a range of numbers
(the `stop` value is not included):

In [37]:
print(np.arange(0, 10, 2))

[0 2 4 6 8]


**`np.zeros(n)`** and **`np.ones(n)`** make arrays filled with 0s or 1s:

In [38]:
print(np.zeros(5))
print(np.ones(4))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]


**`np.full(n, value)`** fills an array with any value you choose:

In [39]:
print(np.full(5, 7))

[7 7 7 7 7]


**`np.linspace(start, stop, num)`** gives `num` **evenly spaced** numbers
(here the `stop` value *is* included):

In [40]:
print(np.linspace(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


You can make a **random** array too. Setting a *seed* first makes the result
repeatable, so you get the same numbers every run:

In [41]:
np.random.seed(42)
print(np.random.randint(1, 10, size=5))

[7 4 8 5 7]


## 2. Array Information

Every array carries useful details about itself.

`ndim` = number of dimensions (1 for a 1-D array), `size` = how many elements,
`dtype` = the type of the numbers inside:

In [42]:
arr = np.array([10, 20, 30, 40, 50])
print("ndim :", arr.ndim)
print("size :", arr.size)
print("dtype:", arr.dtype)

ndim : 1
size : 5
dtype: int64


**`len()`** also gives the number of elements in a 1-D array:

In [43]:
arr = np.array([10, 20, 30, 40, 50])
print(len(arr))

5


## 3. Accessing Elements

You reach into an array just like a list — with indexing and slicing — plus a few
extra NumPy tricks.

Get **one element** by its position (starts at 0). Negative counts from the end:

In [44]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])     # first
print(arr[-1])    # last

10
50


**Slice** a piece with `[start:stop]` (the `stop` position is not included):

In [45]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])

[20 30 40]


**Steps** and **reversing** work too:

In [46]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[::2])     # every second element
print(arr[::-1])    # reversed

[10 30 50]
[50 40 30 20 10]


**Fancy indexing** — grab several positions at once using a list of indexes:

In [47]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[[0, 2, 4]])

[10 30 50]


Arrays are **changeable** — set a single element to a new value:

In [48]:
arr = np.array([10, 20, 30, 40, 50])
arr[0] = 100
print(arr)

[100  20  30  40  50]


You can even change a **whole slice** in one go:

In [49]:
arr = np.array([10, 20, 30, 40, 50])
arr[1:3] = 0
print(arr)

[10  0  0 40 50]


## 4. Mathematical Operators (element-wise)

This is NumPy's superpower: an operation applies to **every element at once**, with
**no loop needed**. This is called *element-wise* (or *vectorised*) maths.

Add a number to **every** element at once:

In [50]:
arr = np.array([1, 2, 3, 4, 5])
print(arr + 10)

[11 12 13 14 15]


Subtract, multiply, and divide — all element-wise:

In [51]:
arr = np.array([1, 2, 3, 4, 5])
print(arr - 1)
print(arr * 2)
print(arr / 2)

[0 1 2 3 4]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


Powers `**` and remainders `%` work the same way:

In [52]:
arr = np.array([1, 2, 3, 4, 5])
print(arr ** 2)
print(arr % 2)

[ 1  4  9 16 25]
[1 0 1 0 1]


Add **two arrays** — matching positions are combined:

In [53]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a + b)

[11 22 33]


See the difference from a normal list: `*` **repeats** a list, but
**multiplies** an array:

In [54]:
py_list = [1, 2, 3]
arr = np.array([1, 2, 3])
print(py_list * 2)    # list is repeated
print(arr * 2)        # array values are multiplied

[1, 2, 3, 1, 2, 3]
[2 4 6]


## 5. Useful Functions

NumPy has fast built-in functions for common calculations.

**Totals and averages** with `np.sum` and `np.mean`:

In [55]:
arr = np.array([4, 8, 15, 16, 23, 42])
print("Sum :", np.sum(arr))
print("Mean:", np.mean(arr))

Sum : 108
Mean: 18.0


**Biggest, smallest, middle** with `np.max`, `np.min`, `np.median`:

In [56]:
arr = np.array([4, 8, 15, 16, 23, 42])
print("Max   :", np.max(arr))
print("Min   :", np.min(arr))
print("Median:", np.median(arr))

Max   : 42
Min   : 4
Median: 15.5


**`np.sqrt()`** finds the square root of **every** element:

In [57]:
arr = np.array([1, 4, 9, 16])
print(np.sqrt(arr))

[1. 2. 3. 4.]


**`np.sort()`** returns the array neatly in order:

In [58]:
arr = np.array([3, 1, 4, 1, 5, 9, 2])
print(np.sort(arr))

[1 1 2 3 4 5 9]


Many functions also work as **methods** (called with a dot):

In [59]:
arr = np.array([4, 8, 15])
print(arr.sum())
print(arr.mean())
print(arr.max())

27
9.0
15


**`np.argmax` / `np.argmin`** give the **position** of the biggest / smallest
value (not the value itself):

In [60]:
arr = np.array([4, 8, 15, 16, 23, 42])
print("Position of max:", np.argmax(arr))
print("Position of min:", np.argmin(arr))

Position of max: 5
Position of min: 0


## 6. Relational (Comparison) Operators

Comparing an array with a value checks **every element** and returns an array of
`True`/`False`. This is the key to **filtering** data.

**`arr > 10`** checks each element and answers `True` or `False` for each one:

In [61]:
arr = np.array([5, 12, 18, 3, 25])
print(arr > 10)

[False  True  True False  True]


Every comparison works this way — `==`, `<=`, and so on:

In [62]:
arr = np.array([5, 12, 18, 3, 25])
print(arr == 18)
print(arr <= 5)

[False False  True False False]
[ True False False  True False]


**Boolean indexing** — keep only the elements that pass the test.
Put the condition inside the brackets:

In [63]:
arr = np.array([5, 12, 18, 3, 25])
print(arr[arr > 10])

[12 18 25]


**Combine conditions** with `&` (and) and `|` (or).
Wrap each condition in parentheses `( )`:

In [64]:
arr = np.array([5, 12, 18, 3, 25])
print(arr[(arr > 5) & (arr < 20)])

[12 18]


**Count** how many elements pass a test. `True` counts as 1, so `np.sum` works:

In [65]:
arr = np.array([5, 12, 18, 3, 25])
print(np.sum(arr > 10))

3


**`np.any`** asks "is at least one True?" and **`np.all`** asks "are they all
True?":

In [66]:
arr = np.array([5, 12, 18, 3, 25])
print(np.any(arr > 20))
print(np.all(arr > 0))

True
True


---

## Well done!

You have learned and run, with the **NumPy** library:

- **Creating arrays** — `np.array`, `arange`, `zeros`, `ones`, `full`, `linspace`, random
- **Array info** — `ndim`, `size`, `dtype`, `len`
- **Accessing** — indexing, slicing, steps, reversing, fancy indexing, changing values
- **Maths operators** — element-wise `+`, `-`, `*`, `/`, `**`, `%`, and array + array
- **Functions** — `sum`, `mean`, `max`, `min`, `median`, `sqrt`, `sort`, `argmax`, `argmin`
- **Relational operators** — `>`, `==`, boolean indexing, `&`/`|`, `any`, `all`

### Try it yourself
1. Make an array of the numbers 1 to 10 using `np.arange`.
2. From `np.array([12, 5, 8, 20, 3])`, print the mean and the biggest value.
3. Multiply every element of `np.array([2, 4, 6])` by 5.
4. From `np.array([10, 25, 30, 5, 40])`, keep only the elements greater than 20.
5. Count how many elements in `np.array([1, 6, 3, 9, 4, 8])` are even
   *(hint: `np.sum(arr % 2 == 0)`)*.

You've taken your first big step into data science with NumPy — brilliant! 🐍